### ISSUE TITLE
Restart

### ISSUE THREAD

**Issue by SpasmaticAA** [KRHS-GameProgramming-2018/Dual-Breakout#5]
No way to restart the game. Exits game entirely. Also should have it go back to title screen or difficulty select

**Comment by YaBoiTuckTruck** [comment]
This is a known error. We will be trying to get end game screens in.

**Comment by YaBoiTuckTruck** [comment]
We have fixed this issue and added the feature "Menu" when a player wins. You can also exit the game from there to.
